"""initial production schema

Revision ID: 9140020dff13
Revises: 
Create Date: 2026-07-20 00:01:07.326306
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9140020dff13'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('actor', sa.String(length=200), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_access_audit_action'), 'access_audit', ['action'], unique=False)
    op.create_index(op.f('ix_access_audit_username'), 'access_audit', ['username'], unique=False)
    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('business_number', sa.String(length=80), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suppliers_name'), 'suppliers', ['name'], unique=True)
    op.create_table('user_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_accounts_active'), 'user_accounts', ['active'], unique=False)
    op.create_index(op.f('ix_user_accounts_role'), 'user_accounts', ['role'], unique=False)
    op.create_index(op.f('ix_user_accounts_username'), 'user_accounts', ['username'], unique=True)
    op.create_table('contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('contract_number', sa.String(length=100), nullable=False),
    sa.Column('standing_offer_number', sa.String(length=100), nullable=True),
    sa.Column('call_up_number', sa.String(length=100), nullable=True),
    sa.Column('project_number', sa.String(length=100), nullable=True),
    sa.Column('procurement_type', sa.String(length=100), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=False),
    sa.Column('department', sa.String(length=200), nullable=False),
    sa.Column('contract_value', sa.Float(), nullable=True),
    sa.Column('performance_evaluation_required', sa.Boolean(), nullable=False),
    sa.Column('performance_regime', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contracts_contract_number'), 'contracts', ['contract_number'], unique=True)
    op.create_index(op.f('ix_contracts_procurement_type'), 'contracts', ['procurement_type'], unique=False)
    op.create_index(op.f('ix_contracts_region'), 'contracts', ['region'], unique=False)
    op.create_index(op.f('ix_contracts_status'), 'contracts', ['status'], unique=False)
    op.create_index(op.f('ix_contracts_supplier_id'), 'contracts', ['supplier_id'], unique=False)
    op.create_table('user_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_sessions_expires_at'), 'user_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_user_sessions_token_hash'), 'user_sessions', ['token_hash'], unique=True)
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_table('evaluations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=30), nullable=False),
    sa.Column('evaluation_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('evaluator', sa.String(length=200), nullable=False),
    sa.Column('scores', sa.JSON(), nullable=False),
    sa.Column('weights', sa.JSON(), nullable=True),
    sa.Column('ratings', sa.JSON(), nullable=False),
    sa.Column('issues', sa.JSON(), nullable=False),
    sa.Column('comments', sa.Text(), nullable=False),
    sa.Column('total_score', sa.Float(), nullable=False),
    sa.Column('outcome', sa.String(length=60), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluations_contract_id'), 'evaluations', ['contract_id'], unique=False)
    op.create_index(op.f('ix_evaluations_model'), 'evaluations', ['model'], unique=False)
    op.create_index(op.f('ix_evaluations_outcome'), 'evaluations', ['outcome'], unique=False)
    op.create_index(op.f('ix_evaluations_status'), 'evaluations', ['status'], unique=False)
    op.create_table('attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evaluation_id', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=120), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('uploaded_by', sa.String(length=200), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['evaluation_id'], ['evaluations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attachments_evaluation_id'), 'attachments', ['evaluation_id'], unique=False)
    op.create_table('audit_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evaluation_id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(length=200), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=True),
    sa.Column('original_value', sa.Text(), nullable=True),
    sa.Column('revised_value', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['evaluation_id'], ['evaluations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_entries_evaluation_id'), 'audit_entries', ['evaluation_id'], unique=False)
    op.create_table('evaluation_project_details',
    sa.Column('evaluation_id', sa.Integer(), nullable=False),
    sa.Column('client_reference_number', sa.String(length=100), nullable=True),
    sa.Column('description_of_work', sa.Text(), nullable=True),
    sa.Column('firm_address', sa.Text(), nullable=True),
    sa.Column('contractor_superintendent', sa.String(length=200), nullable=True),
    sa.Column('project_manager_name', sa.String(length=200), nullable=True),
    sa.Column('project_manager_telephone', sa.String(length=50), nullable=True),
    sa.Column('project_manager_fax', sa.String(length=50), nullable=True),
    sa.Column('project_manager_cell', sa.String(length=50), nullable=True),
    sa.Column('project_manager_email', sa.String(length=254), nullable=True),
    sa.Column('contract_award_amount', sa.Float(), nullable=True),
    sa.Column('contract_award_date', sa.Date(), nullable=True),
    sa.Column('final_amount', sa.Float(), nullable=True),
    sa.Column('contract_completion_date', sa.Date(), nullable=True),
    sa.Column('contract_changes_count', sa.Integer(), nullable=True),
    sa.Column('final_certificate_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['evaluation_id'], ['evaluations.id'], ),
    sa.PrimaryKeyConstraint('evaluation_id')
    )
    op.create_table('evaluation_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evaluation_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('user', sa.String(length=200), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['evaluation_id'], ['evaluations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluation_versions_evaluation_id'), 'evaluation_versions', ['evaluation_id'], unique=False)
    op.create_table('performance_decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('evaluation_id', sa.Integer(), nullable=True),
    sa.Column('decision_type', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('notice_date', sa.Date(), nullable=True),
    sa.Column('representation_deadline', sa.Date(), nullable=True),
    sa.Column('representations_summary', sa.Text(), nullable=True),
    sa.Column('legal_review_reference', sa.String(length=200), nullable=True),
    sa.Column('delegated_authority_reference', sa.String(length=200), nullable=True),
    sa.Column('authority', sa.String(length=200), nullable=False),
    sa.Column('recorded_by', sa.String(length=200), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['evaluation_id'], ['evaluations.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_performance_decisions_decision_type'), 'performance_decisions', ['decision_type'], unique=False)
    op.create_index(op.f('ix_performance_decisions_evaluation_id'), 'performance_decisions', ['evaluation_id'], unique=False)
    op.create_index(op.f('ix_performance_decisions_status'), 'performance_decisions', ['status'], unique=False)
    op.create_index(op.f('ix_performance_decisions_supplier_id'), 'performance_decisions', ['supplier_id'], unique=False)
    op.create_table('decision_audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('decision_id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(length=200), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('original_status', sa.String(length=30), nullable=True),
    sa.Column('revised_status', sa.String(length=30), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['performance_decisions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decision_audit_decision_id'), 'decision_audit', ['decision_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_decision_audit_decision_id'), table_name='decision_audit')
    op.drop_table('decision_audit')
    op.drop_index(op.f('ix_performance_decisions_supplier_id'), table_name='performance_decisions')
    op.drop_index(op.f('ix_performance_decisions_status'), table_name='performance_decisions')
    op.drop_index(op.f('ix_performance_decisions_evaluation_id'), table_name='performance_decisions')
    op.drop_index(op.f('ix_performance_decisions_decision_type'), table_name='performance_decisions')
    op.drop_table('performance_decisions')
    op.drop_index(op.f('ix_evaluation_versions_evaluation_id'), table_name='evaluation_versions')
    op.drop_table('evaluation_versions')
    op.drop_table('evaluation_project_details')
    op.drop_index(op.f('ix_audit_entries_evaluation_id'), table_name='audit_entries')
    op.drop_table('audit_entries')
    op.drop_index(op.f('ix_attachments_evaluation_id'), table_name='attachments')
    op.drop_table('attachments')
    op.drop_index(op.f('ix_evaluations_status'), table_name='evaluations')
    op.drop_index(op.f('ix_evaluations_outcome'), table_name='evaluations')
    op.drop_index(op.f('ix_evaluations_model'), table_name='evaluations')
    op.drop_index(op.f('ix_evaluations_contract_id'), table_name='evaluations')
    op.drop_table('evaluations')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_token_hash'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_expires_at'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_contracts_supplier_id'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_status'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_region'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_procurement_type'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_contract_number'), table_name='contracts')
    op.drop_table('contracts')
    op.drop_index(op.f('ix_user_accounts_username'), table_name='user_accounts')
    op.drop_index(op.f('ix_user_accounts_role'), table_name='user_accounts')
    op.drop_index(op.f('ix_user_accounts_active'), table_name='user_accounts')
    op.drop_table('user_accounts')
    op.drop_index(op.f('ix_suppliers_name'), table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_index(op.f('ix_access_audit_username'), table_name='access_audit')
    op.drop_index(op.f('ix_access_audit_action'), table_name='access_audit')
    op.drop_table('access_audit')
    # ### end Alembic commands ###
